// daiguozhou 20190903, copy from android build of release version 76.0.3809.111.
//
// Generated by build/write_buildflag_header.py
// From "//base:synchronization_buildflags"

#ifndef BASE_SYNCHRONIZATION_SYNCHRONIZATION_BUILDFLAGS_H_
#define BASE_SYNCHRONIZATION_SYNCHRONIZATION_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_ENABLE_MUTEX_PRIORITY_INHERITANCE() (0)

#endif  // BASE_SYNCHRONIZATION_SYNCHRONIZATION_BUILDFLAGS_H_
