// daiguozhou 20190903, copy from android build of release version 76.0.3809.111.
//
// Generated by build/write_buildflag_header.py
// From "//base:anchor_functions_buildflags"

#ifndef BASE_ANDROID_LIBRARY_LOADER_ANCHOR_FUNCTIONS_BUILDFLAGS_H_
#define BASE_ANDROID_LIBRARY_LOADER_ANCHOR_FUNCTIONS_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_USE_LLD() (1)
#define BUILDFLAG_INTERNAL_SUPPORTS_CODE_ORDERING() (1)

#endif  // BASE_ANDROID_LIBRARY_LOADER_ANCHOR_FUNCTIONS_BUILDFLAGS_H_
