// daiguozhou 20190903, copy from android build of release version 76.0.3809.111.
//
// Generated by build/write_buildflag_header.py
// From "//base:logging_buildflags"

#ifndef BASE_LOGGING_BUILDFLAGS_H_
#define BASE_LOGGING_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_ENABLE_LOG_ERROR_NOT_REACHED() (0)

#endif  // BASE_LOGGING_BUILDFLAGS_H_
