// daiguozhou 20190903, copy from android build of release version 76.0.3809.111.
//
// Generated by build/write_buildflag_header.py
// From "//base:partition_alloc_buildflags"

#ifndef BASE_PARTITION_ALLOC_BUILDFLAGS_H_
#define BASE_PARTITION_ALLOC_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_USE_PARTITION_ALLOC() (1)

#endif  // BASE_PARTITION_ALLOC_BUILDFLAGS_H_
