// daiguozhou 20190903, copy from android build of release version 76.0.3809.111.
//
// Generated by build/write_buildflag_header.py
// From "//base:protected_memory_buildflags"

#ifndef BASE_MEMORY_PROTECTED_MEMORY_BUILDFLAGS_H_
#define BASE_MEMORY_PROTECTED_MEMORY_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_USE_LLD() (1)

#endif  // BASE_MEMORY_PROTECTED_MEMORY_BUILDFLAGS_H_
